[build]
  functions = "netlify/functions"
  node_bundler = "esbuild"
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
[functions]
  included_files = ["src/**"]
[dev]
  autoLaunch = false
